Altered to work with Java 8 and 9+ JREs
karlsabo/packr pull request #8
Opened 2020-04-27 19:47 UTC by cmiles74

Altered "searchJRE" logic to work with Java 9+

Starting with Java 9, the JRE is no longer bundled in a separate directory named "jre". Instead everything is lumped is in the root directory of the JDK/JRE. This change allows Packr to work with either a Java 8 or a Java 9 style JRE/JDK.

I have tested this with OpenJDK 8 and 9 JREs.

Thank you!

2020-04-27 20:47 UTC, cmiles74 commented
This is really weird, it failed with the error...

`jre/lib/amd64/server/libjvm.so: cannot open shared object file: No such file or directory`

I'm not sure this is related to the project's code, it could be the VM doing the build is running on a different platform. But I am just guessing.

2020-04-28 05:36 UTC, karlsabo commented
This is only a tiny part of the issue. Packr Launcher is what loads the shared libraries to start up the JRE.

Look at packr_win32.cpp for the function loadJNIFunctions.

2020-04-28 13:30 UTC, cmiles74 commented
Okay, I will take a look at it later today.` :-)`

When we build with Java 8, we end up with the `java` exectuable in `jre\bin\java`, with this change Java 9 the `java` exectuable is in the same place, `jre\bin\java`. Looking closer at the Java 8 build I can see that it's not exactly the same... I will also spend more time testing a Java 8 build, too.

2020-04-28 15:24 UTC, cmiles74 commented
I've changed the way it searches for the JRE; first it searches for a Java 8 style and if that fails, then it searches for a Java 9 style. I have tested with with Java 8 from OpenJDK and a custom Java 11 image, in both cases the resulting layout of the JRE in the target location is the same.

Since the files are in the same place, the launcher doesn't have a problem finding the files that it needs.  `:-)`

As an aside, I found that on a x64 Windows 10 system the launcher would fail if I paired it with a 32 bit JDK.

> Error code [193] when trying to load jvm.dll: 000001D0E30B9090
> Error: failed to load VM runtime library!

Switching to a 64 bit JDK resolved this issue.

2020-04-29 04:10 UTC, karlsabo commented
Seems reasonable, I wish there was a cleaner way. Can you please add JDK 11 test cases to https://github.com/karlsabo/packr/blob/master/PackrAllTestApp/packrAllTestApp.gradle.kts

Look at:
```
// Linux x86-64
         JdkDownloadInformation(uri("https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u252-b09/OpenJDK8U-jdk_x64_linux_hotspot_8u252b09.tar.gz").toURL(),
               "2b59b5282ff32bce7abba8ad6b9fde34c15a98f949ad8ae43e789bbd78fc8862"),
```

And add AdoptOpenJDK links for JDK 11 linux, mac, and Windows. I suspect it's not going to work for Linux based on the moved libjvm.so file being moved.

```text
Java 8
linux-x86-64-jdk8u252-b09\jre\lib\amd64\server\libjvm.so
macos-x86-64-jdk8u252-b09\Contents\Home\jre\lib\server\libjvm.dylib
windows-x86-64-jdk8u252-b09\jre\bin\server\jvm.dll
   
Java 11
linux-x86-64-jdk-11.0.7+10\lib\server\libjvm.so
macos-x86-64-jdk-11.0.7+10\Contents\Home\lib\server\libjvm.dylib
windows-x86-64-jdk-11.0.7+10\bin\server\jvm.dll
```

2020-04-29 04:13 UTC, karlsabo requested changes
Please add JDK 11 tests to the PackrAllTestApp.

2020-04-29 04:15 UTC, karlsabo commented
Oh about the 32-bit JDK. I've been meaning to update the readme. I removed all x86 (32-bit) compile targets.

2020-04-29 20:25 UTC, cmiles74 commented
I ended up changing the way the Linux launcher looks for `libjvm.so`, just as you has suspected. It now checks for the way it is in Java 9, then the 64-bit location for Java 8 and lastly the 32-bit location for Java 8.

I don't write a lot of C++, let me know if you'd like me to take another stab at this.

2020-04-30 03:36 UTC, karlsabo requested changes
Only some minor typos to clean up. Looks good otherwise,, thanks for this!

I'm not a C++ expert either, especially with system dependent libraries. Stat seems like a fine approach, sure it'd be great to convert it to C++17 and use the filesystem API but that's a lot of effort for a little reward :D.

Thanks again, I thought this was going to be a hard problem to solve and I didn't have to type a line of code to get it done 😂.

2020-04-30 03:36 UTC, karlsabo commented on PackrAllTestApp/packrAllTestApp.gradle.kts
> +         // macOS x86-64 Java 9
Minor comment typo saying Java 9 instead of Java 8

2020-04-30 03:36 UTC, karlsabo commented on PackrAllTestApp/packrAllTestApp.gradle.kts
> +         // Windows x86-64 Java 9
Typo

2020-04-30 12:23 UTC, cmiles74 commented
I am glad I could help out. :smile: I fixed those typos, this should be all set.

2020-04-30 23:54 UTC, merged

2020-04-30 23:58 UTC, karlsabo commented
Thanks, I'll try to release version 2.4.0 this week!